# Generated by Django 4.2.10 on 2024-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_balance_amount_balance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Количество бонусов'),
        ),
    ]
