# Generated by Django 4.2.10 on 2024-08-20 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_group_options_alter_lesson_course'),
        ('users', '0003_alter_balance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='Subscriber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь подписки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subscription',
            name='course',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='courses.course', verbose_name='Курс подписки'),
            preserve_default=False,
        ),
    ]
