# Generated by Django 4.2.10 on 2024-08-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.PositiveBigIntegerField(default=1000, verbose_name='Цена'),
        ),
    ]
