# Generated by Django 4.2.10 on 2024-08-17 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Уроки'),
        ),
    ]
